services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer:
    build: ./producer
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  consumer:
    build: ./consumer
    ports:
      - "3001:3001"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
